env:
  es6: true
  es2016: true
  es2017: true
  es2018: true
  es2019: true
  es2020: true
  es2021: true
  es2022: true
  commonjs: true
globals:
  clearTimeout: true
  clearInterval: true
  console: true
  globalThis: true
  setTimeout: true
  setInterval: true
  Intl: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  no-undef:
    - error
    - typeof: false
  no-restricted-globals:
    - error
    - escape
    - unescape
    - eval
  no-restricted-modules:
    - error
    - assert
    - async_hooks
    - buffer
    - child_process
    - cluster
    - console
    - constants
    - crypto
    - dgram
    - diagnostics_channel
    - dns
    - domain
    - events
    - fs
    - http
    - http2
    - https
    - inspector
    - module
    - net
    - os
    - path
    - perf_hooks
    - process
    - punycode
    - querystring
    - readline
    - repl
    - stream
    - string_decoder
    - test
    - timers
    - tls
    - trace_events
    - tty
    - url
    - util
    - v8
    - vm
    - wasi
    - worker_threads
    - zlib